name=ESP32_Samsung
version=1.0.0
author=Richard McDougall
maintainer=richardmcd
sentence=ESP32 Samsung RS485
paragraph=
category=Communication
url=https://github.com/rjmcdougall/ESP32_Samsung
architectures=*
includes=esp32_samsung.h